# Generated by Django 2.1.3 on 2018-12-04 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Your first name', max_length=50, unique=True)),
                ('last_name', models.CharField(help_text='Your last name', max_length=50, unique=True)),
                ('date_of_birth', models.PositiveIntegerField(help_text='Your birth')),
                ('graduation_year', models.PositiveIntegerField(help_text='Your expected graduation year')),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Member')),
            ],
            bases=('accounts.member',),
        ),
    ]
