# Generated by Django 2.1.3 on 2018-12-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181205_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(help_text='Your birth'),
        ),
        migrations.AlterField(
            model_name='member',
            name='graduation_year',
            field=models.PositiveIntegerField(default=2018, help_text='Your expected graduation year'),
        ),
    ]
