# Generated by Django 2.1.3 on 2018-12-09 17:49

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181206_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superadmin',
            options={},
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', accounts.managers.MemberManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='superadmin',
            managers=[
                ('objects', accounts.managers.MemberManager()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(help_text='Your birth (MM/DD/YYYY)', verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(help_text='Your email', max_length=40, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(help_text='Your first name', max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='graduation_year',
            field=models.PositiveIntegerField(default=2018, help_text='Your expected graduation year', verbose_name='graduation year'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(help_text='Your last name', max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='specialized',
            field=models.CharField(choices=[('T', 'Tech'), ('B', 'Builder'), ('O', 'Other')], default='O', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(help_text='Your username', max_length=20, unique=True, verbose_name='username'),
        ),
    ]
